name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install Cython
      run: |
        pip install cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: '34'
        build-tools-version: '34.0.0' # Or the latest 34.x.x version

    - name: Download NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d $HOME/android-ndk-r27c

    - name: Create buildozer.spec
      run: |
        buildozer init
        sed -i 's/requirements =/requirements = python3,kivy,pyttsx3,speechrecognition/' buildozer.spec
        sed -i 's/android.api = 31/android.api = 34/' buildozer.spec
        sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/android.ndk_path =/android.ndk_path = \/home\/runner\/android-ndk-r27c/' buildozer.spec
        sed -i 's/android.permissions =/android.permissions = RECORD_AUDIO/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Helper-APK
        path: bin/*.apk
