# Workflow name
name: Build Android APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installs Python dependencies (Buildozer)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      # Installs Cython (often required by Kivy recipes)
      - name: Install Cython
        run: |
          pip install cython

      # *** NEW: Set up Android Environment Manually ***
      - name: Set up Android Environment Manually
        run: |
          # Define SDK root path
          SDK_ROOT=$HOME/android-sdk
          echo "ANDROID_HOME=${SDK_ROOT}" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${SDK_ROOT}" >> $GITHUB_ENV
          mkdir -p ${SDK_ROOT}

          # Download and unzip latest command-line tools
          # URL might change, check Android Studio site for latest if this fails
          echo "Downloading command-line tools..."
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          mkdir -p ${SDK_ROOT}/cmdline-tools
          unzip cmdline-tools.zip -d ${SDK_ROOT}/cmdline-tools
          # Create the 'latest' directory structure
          mv ${SDK_ROOT}/cmdline-tools/cmdline-tools ${SDK_ROOT}/cmdline-tools/latest
          echo "Command-line tools installed to ${SDK_ROOT}/cmdline-tools/latest"

          # Add cmdline-tools bin to PATH for subsequent sdkmanager commands
          SDKMANAGER_PATH=${SDK_ROOT}/cmdline-tools/latest/bin
          echo "${SDKMANAGER_PATH}" >> $GITHUB_PATH

          # Install platform-tools and specific build-tools version
          BUILD_TOOLS_VERSION=33.0.2
          echo "Installing platform-tools and build-tools ${BUILD_TOOLS_VERSION}..."
          sdkmanager --sdk_root=${SDK_ROOT} "platform-tools" "build-tools;${BUILD_TOOLS_VERSION}" || echo "sdkmanager install failed"

          # Add platform-tools and build-tools to PATH for the rest of the job
          echo "${SDK_ROOT}/platform-tools" >> $GITHUB_PATH
          echo "${SDK_ROOT}/build-tools/${BUILD_TOOLS_VERSION}" >> $GITHUB_PATH

          # Accept licenses for this SDK root
          echo "Accepting licenses..."
          yes | sdkmanager --licenses --sdk_root=${SDK_ROOT} || echo "sdkmanager licenses failed"

          echo "Listing installed packages:"
          sdkmanager --list_installed --sdk_root=${SDK_ROOT}

          echo "Final PATH: $PATH"

      # *** NEW: Download NDK r25b Manually ***
      - name: Download NDK r25b
        run: |
          echo "Downloading NDK r25b..."
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk-r25b.zip
          unzip android-ndk-r25b.zip -d $HOME/ndk
          # Rename the extracted folder to a known name
          mv $HOME/ndk/android-ndk-r25b $HOME/android-ndk-r25b
          echo "NDK r25b installed to $HOME/android-ndk-r25b"

      # Set up Java 11 (Recommended for broader compatibility with Android tooling)
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Creates and configures the buildozer.spec file to use the manual setup
      - name: Create buildozer.spec
        run: |
          buildozer init
          sed -i 's/requirements =/requirements = python3,kivy,pyttsx3,speechrecognition/' buildozer.spec
          sed -i 's/android.api = 31/android.api = 34/' buildozer.spec
          sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
          sed -i 's/#android.permissions =/android.permissions = RECORD_AUDIO/' buildozer.spec
          # *** Point to manually installed SDK and NDK ***
          sed -i 's|#android.sdk_path =|android.sdk_path = /home/runner/android-sdk|' buildozer.spec
          sed -i 's|#android.ndk_path =|android.ndk_path = /home/runner/android-ndk-r25b|' buildozer.spec
          # *** Set specific build-tools and NDK versions ***
          sed -i 's/#android.build_tools_version =/android.build_tools_version = 33.0.2/' buildozer.spec
          sed -i 's/#android.ndk = 25b/android.ndk = 25b/' buildozer.spec

      # Builds the Android APK
      - name: Build APK
        run: |
          echo "Running Buildozer..."
          # Check effective paths just before build
          echo "Effective ANDROID_HOME: $ANDROID_HOME"
          echo "Effective PATH: $PATH"
          which sdkmanager
          which adb
          which aidl || echo "aidl not found by which"
          buildozer -v android debug

      # Uploads the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Helper-APK
          path: bin/*.apk

