# Workflow name
name: Build Android APK via Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Runner just needs Docker

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image using the Dockerfile in the repo root
      - name: Build Docker image
        run: docker build -t helper-app-builder .

      # Run Buildozer inside the container
      # Mount the current directory ($GITHUB_WORKSPACE) into /app inside the container
      # Run as current user (matching runner user) to avoid output file permission issues
      - name: Build APK with Buildozer
        run: >
          docker run --rm
          --user=$(id -u):$(id -g)
          -v "${GITHUB_WORKSPACE}:/app"
          helper-app-builder
          buildozer -v android debug

      # Upload the generated APK (adjust path if needed based on buildozer output)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Helper-APK
          # Path relative to GITHUB_WORKSPACE where buildozer outputs the APK
          path: bin/*.apk
          # Optional: If no file is found, don't fail the workflow
          if-no-files-found: ignore


