name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install Cython
      run: |
        pip install cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        packages: 'cmdline-tools-version;11.0 platform-tools build-tools;34.5.0'
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: false

    - name: Download NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d $HOME/android-ndk-r27c

    - name: Create buildozer.spec
      run: |
        buildozer init
        sed -i 's/requirements =/requirements = python3,kivy,pyttsx3,speechrecognition/' buildozer.spec
        sed -i 's/android.api = 31/android.api = 34/' buildozer.spec
        sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/android.ndk_path =/android.ndk_path = \/home\/runner\/android-ndk-r27c/' buildozer.spec
        sed -i 's/android.permissions =/android.permissions = RECORD_AUDIO/' buildozer.spec

     - name: Build APK
      run: |
        echo "--- Debugging Environment ---"
        echo "1. ANDROID_HOME: $ANDROID_HOME"
        echo "2. ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "3. Current PATH: $PATH"
        
        echo "4. Checking SDK Structure..."
        ls -la $ANDROID_HOME/build-tools/ || echo "Could not list $ANDROID_HOME/build-tools/"
        ls -la $ANDROID_HOME/build-tools/34.0.0/ || echo "Could not list $ANDROID_HOME/build-tools/34.0.0/"
        
        echo "5. Searching for aidl..."
        find $ANDROID_HOME -name aidl || echo "aidl not found via find command"
        
        echo "6. Attempting 'which aidl' after potential PATH export:"
        export PATH="$ANDROID_HOME/build-tools/34.0.0:$PATH" # Keep the export attempt for now
        echo "   Updated PATH: $PATH" 
        which aidl || echo "aidl not found via which command"
        echo "--- End Debugging ---"

        # Now attempt the buildozer command again
        buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Helper-APK
        path: bin/*.apk
